version: "3.9"

volumes:
  pgdata:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:6969:5432

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 127.0.0.1:42069:6379
